### ISSUE TITLE
Lua error when enabling tiptac+elvui

### ISSUE THREAD

**Issue by lowpita** [frozn/TipTac#174]
**Describe the bug**
Hey. This error pops up whenever I have elvui enabled with tiptac although I have elvui's tooltips disabled (only running tiptac for it).  Also the mouse anchor y offset doesn't seem to be chaning anything while having all the tooltip units and tips anchored to mouseover. The x offset for this is working fine tho. All the above didn't happen before 23.01.23 update.

507x SharedXML/Backdrop.lua:189: attempt to index field 'backdropInfo' (a nil value)
[string "@SharedXML/Backdrop.lua"]:189: in function `GetEdgeSize'
[string "@SharedXML/Backdrop.lua"]:218: in function `SetupTextureCoordinates'
[string "@SharedXML/Backdrop.lua"]:325: in function <SharedXML/Backdrop.lua:294>
[string "=[C]"]: in function `ApplyBackdrop'
[string "@SharedXML/Backdrop.lua"]:341: in function <SharedXML/Backdrop.lua:329>
[string "=[C]"]: in function `SetBackdrop'
[string "@ElvUI/Core/General/Toolkit.lua"]:163: in function `SetTemplate'
[string "@ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:789: in function <ElvUI/Core/Modules/Tooltip/Tooltip.lua:782>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SharedTooltip_SetBackdropStyle'
[string "@FrameXML/GameTooltip.lua"]:449: in function <FrameXML/GameTooltip.lua:446>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@TipTac/ttCore.lua"]:2434: in function <TipTac/ttCore.lua:2398>
[string "=[C]"]: ?

Locals:
self = Frame {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 template = "Transparent"
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined =[C]:-1
 GetCenterColor = <function> defined @SharedXML/NineSlice.lua:255
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetCenterColor = <function> defined =[C]:-1
 GetFrameLayoutTextureKit = <function> defined @SharedXML/NineSlice.lua:236
 SetVertexColor = <function> defined @SharedXML/NineSlice.lua:285
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 GetBorderColor = <function> defined @SharedXML/NineSlice.lua:273
 TopRightCorner = Texture {
 }
 Center = Texture {
 }
 customBackdropAlpha = 1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 0 = <userdata>
 OnLoad = <function> defined @SharedXML/NineSlice.lua:241
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 TopLeftCorner = Texture {
 }
 ClearBackdrop = <function> defined =[C]:-1
 GetFrameLayoutType = <function> defined @SharedXML/NineSlice.lua:232
 BottomRightCorner = Texture {
 }
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 SetBorderColor = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = "attempt to index field 'backdropInfo' (a nil value)"
defaultEdgeSize = 39

**To Reproduce**
1. Enable tiptac and elvui.
2. Mouseover any unit.
3. See error.

**Expected behavior**

**Screenshots**
https://imgur.com/JX1Eklq

**TipTac Reborn (please complete the following information):**
 - Version 23.01.23

**WoW (please complete the following information):**
 - Flavor: Retail.
 - Version 10.0.2.

**Additional context**
Tested this with only elvui and tiptac to confirm it only happens with these addons.

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Fixed with next release.

**Comment by lowpita** [comment]
Hi. Thanks for the elvui's part fix. I tested changing the mouse anchor x offset and nothing happened, so I suppose this part wasn't fixed yet (described here too: https://github.com/frozn/TipTac/issues/179 ). I think another issue was introduced in today's release, which makes the frame tip type anchors unchangeable (mine was always anchored to mouseover at top left as you can see in the screenshots I posted before).

**Comment by frozn** [comment]
Mouse offsets (under "Mouse") only are considered if mouse anchoring is involved (under "Anchors"). The bug considering mouse offset y will be included in the next release.

**Comment by lowpita** [comment]
Yeah, sorry, I meant to mention the y offset instead of the x one, which is working fine.
