### ISSUE TITLE
[Suggestion] Having this fork Included in WowUp Hub

### ISSUE THREAD

**Issue by alphabitnz** [frozn/TipTac#3]
Suggestion: Having this fork Included in WowUp Hub

See: https://github.com/WowUp/WowUp/issues/1062

**Comment by frozn** [comment]
I stumbled across informations regarding Wowup... you can install this version from github the following way:

In WowUp, go to Get Addons->Install From URL and enter `https://github.com/frozn/TipTac`

It should update automatically, if a new release is available here.

**Comment by alphabitnz** [comment]
> In WowUp, go to Get Addons->Install From URL and enter `https://github.com/frozn/TipTac`
> 
> It should update automatically, if a new release is available here.

Thanks, I was not aware of that feature. However I get an error:

Input:
![image](https://user-images.githubusercontent.com/9102111/148666479-37842638-2fcf-43ee-a718-9c6719bbeff2.png)

Retail:
![image](https://user-images.githubusercontent.com/9102111/148666480-16623817-e8f2-4ce5-b383-a63e76c93782.png)

Classic (TBC):
![image](https://user-images.githubusercontent.com/9102111/148666489-d1bf0d0b-8357-4094-85ba-be1f1f4917da.png)

Classic (Era/SoM):
![image](https://user-images.githubusercontent.com/9102111/148666503-952d74ca-4681-419e-87e9-18e376ff022f.png)

**Comment by alphabitnz** [comment]
This thread of mine on WowUp seems to have some discussion around this:
https://github.com/WowUp/WowUp/issues/1062#issuecomment-1006034041

**Comment by frozn** [comment]
I updated the releases here on github for WowUp as described here: [https://wowup.io/guide/wowup/hub](https://wowup.io/guide/wowup/hub)

Should work now... :crossed_fingers:

**Comment by alphabitnz** [comment]
> Should work now... 🤞

Is working for retail now, good stuff. However Vanilla and TBC are still not working as WowUp needs their releases as separate zip files with the -classic and -bc filename suffixes respectively.

**Comment by frozn** [comment]
I uploaded two copies of the zip file and renamed them with -classic and -bcc.

Hint: I took a look at the source code of the WowUp client: I picked -bcc instead of -bc, because this works too, same as -tbc.

**Comment by alphabitnz** [comment]
Awesome! Can confirm it's all working for both classic variants now, and good tip on the bcc suffix, I was just going off what the error message said :)
