### ISSUE TITLE
Error Background&Borders Tooltip

### ISSUE THREAD

**Issue by zdinch** [frozn/TipTac#35]
Hello! thanks for keeping this great addon!
Since the last update in TBC it does not show well some backgrounds and borders, such as:

https://puu.sh/IDFfg/23dd902deb.png
https://puu.sh/IDFf5/a26226d4c8.png
https://puu.sh/IFOhQ/d799d46f7b.jpg

Thanks!

**Comment by frozn** [comment]
These dropdown menus have never been styled by TipTac before. Nevertheless I added the styling of DropDownList1/2, LibQTip and LibDBIcon tooltips because it's quite neat.

I committed my changes to the main branch. If you are not familiar to download the current (unreleased) version, here is a zip file with the current build:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/7965146/TipTac-dev.zip)

Looks fine to you?

**Comment by zdinch** [comment]
Good! Thanks a lot! It works perfect!
The only thing that still doesn't work is the friends.

Thanks a lot!

**Comment by frozn** [comment]
You're right. I added the missing FriendsTooltip:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/7965842/TipTac-dev.zip)

Now everything's fine? :slightly_smiling_face:

**Comment by zdinch** [comment]
ohhhh thank you so much!! now everything is perfect!
Thank you very much for continuing to update the addon!

**Comment by frozn** [comment]
Thanks for your kind words! :blush:
