### ISSUE TITLE
[Classic Era] Invalid factory object type

### ISSUE THREAD

**Issue by entroscopy** [frozn/TipTac#57]
Addon started throwing this error yesterday. Tooltips when hovering over players sometimes work as they should, but oftentimes they cut off information below the guild name. Also, certain sections in the options are missing and throw said error when they are opened.

![how they should look](https://user-images.githubusercontent.com/30931739/153744958-6767665c-e0f7-40d1-b52b-fa63a909d470.png)
![information missing](https://user-images.githubusercontent.com/30931739/153744959-6033783d-5ab4-4920-93cd-8165a404322a.png)
![options missing](https://user-images.githubusercontent.com/30931739/153744960-69f97f98-d2cd-47b8-be9c-80eb44cfb416.png)

I'm not sure if you're accepting bug reports for Classic, throwing this out there in case you are.

EDIT: forgot to add, tested with all other addons disabled, only tiptac active.
EDIT2: been downgrading to previous releases and v21.12.22 seems to be the latest release without the options issue/error throwing for me. The information cut off below the guild name exists in that version too.

**Comment by frozn** [comment]
I added the missing embeds for the library `LibSharedMedia-3.0`. It's pretty weird... I had not noticed before that they were missing, because these embeds were supplied through other addons. It's a general issue not related to classic only.

I fixed it in the current dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8056126/TipTac-dev.zip)

It's working fine for you too with this version?

**Comment by entroscopy** [comment]
Yep, the dev version fixed the embeds. Options load fine now.
However, the missing info problem still persists. Apparently caused by TipTacTalents.

![Untitled](https://user-images.githubusercontent.com/30931739/153801479-8967fbf7-7a0b-4477-8ffa-773f0566d56f.png)
![Untitled2](https://user-images.githubusercontent.com/30931739/153801482-3dd7a6d2-ec47-455a-a6d9-334fbabe9307.png)
![Untitled3](https://user-images.githubusercontent.com/30931739/153801487-a352b65c-ed3a-468e-ae44-1904d6a73a56.png)

The level-race-class info doesn't show up until you get into inspect range, where I assume the addon tries to get the talent info and fails because you can't inspect other people's talents pre-BC. Disabling TipTacTalents doesn't appear to fix this.

**Comment by frozn** [comment]
I fixed to issue with the missing infos. Here's the dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8083332/TipTac-dev.zip)

**Comment by entroscopy** [comment]
Yep, that fixed it. Thanks!
