### ISSUE TITLE
Error when interacting with Legionfall Construction Table

### ISSUE THREAD

**Issue by AutolycusWolf** [frozn/TipTac#73]
Upon interacting with  Legionfall Construction Table and when mousing over the CONTRIBUTE button I get the following error:

190x TipTacItemRef\ttItemRef.lua:1838: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@TipTacItemRef\ttItemRef.lua"]:1838: in function `SetBackdropBorderColorLocked'
[string "@TipTacItemRef\ttItemRef.lua"]:2217: in function `quest'
[string "@TipTacItemRef\ttItemRef.lua"]:1040: in function <TipTacItemRef\ttItemRef.lua:1033>
[string "=[C]"]: in function `GameTooltip_AddQuestRewardsToTooltip'
[string "@Blizzard_Contribution\Blizzard_Contribution.lua"]:184: in function <...dOns\Blizzard_Contribution\Blizzard_Contribution.lua:175>

Locals:
self = TipTacItemRef {
 0 = <userdata>
 ApplyHooksToTips = <function> defined @TipTacItemRef\ttItemRef.lua:1413
 ADDON_LOADED = <function> defined @TipTacItemRef\ttItemRef.lua:1571
 ApplyWorkaroundForFirstMouseover = <function> defined @TipTacItemRef\ttItemRef.lua:285
 SetBackdropBorderColorLocked = <function> defined @TipTacItemRef\ttItemRef.lua:1832
 HookTips = <function> defined @TipTacItemRef\ttItemRef.lua:1566
 name = "ItemRef"
 CreateTooltipIcon = <function> defined @TipTacItemRef\ttItemRef.lua:184
 OnApplyConfig = <function> defined @TipTacItemRef\ttItemRef.lua:252
 ApplyHooksToCFGDFI = <function> defined @TipTacItemRef\ttItemRef.lua:1539
 ApplyHooksToGIFIC = <function> defined @TipTacItemRef\ttItemRef.lua:1553
 SetHyperlink_Hook = <function> defined @TipTacItemRef\ttItemRef.lua:428
}
tip = EmbeddedItemTooltip {
 0 = <userdata>
 BottomFontString = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 BottomOverlay = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 TextRight2 = EmbeddedItemTooltipTextRight2 {
 }
 TextLeft2 = EmbeddedItemTooltipTextLeft2 {
 }
 ttSetBackdropBorderColorLocked = false
 TopOverlay = <unnamed> {
 }
 waitingForData = true
 shoppingTooltips = <table> {
 }
 needsReset = true
 updateTooltipTimer = 0.200000
 TextRight1 = EmbeddedItemTooltipTextRight1 {
 }
 textRight2Font = "GameTooltipText"
 textLeft1Font = "GameTooltipHeaderText"
}
lockColor = true
r = 0.500000
g = 0.500000
b = 0.500000
a = 1
(*temporary) = nil
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 BottomFontString = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 BottomOverlay = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 TextRight2 = EmbeddedItemTooltipTextRight2 {
 }
 TextLeft2 = EmbeddedItemTooltipTextLeft2 {
 }
 ttSetBackdropBorderColorLocked = false
 TopOverlay = <unnamed> {
 }
 waitingForData = true
 shoppingTooltips = <table> {
 }
 needsReset = true
 updateTooltipTimer = 0.200000
 TextRight1 = EmbeddedItemTooltipTextRight1 {
 }
 textRight2Font = "GameTooltipText"
 textLeft1Font = "GameTooltipHeaderText"
}
(*temporary) = 0.500000
(*temporary) = 0.500000
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
cfg = <table> {
 fontFace = "Fonts\FRIZQT__.TTF"
 showRealm = "none"
 classification_elite = "Level %s|cffffcc00 Elite"
 barHeight = 6
 tipBackdropEdge = "Tooltips\UI-Tooltip-Border"
 backdropEdgeSize = 16
 hideFactionText = false
 powerBar = false
 fontFlags = ""
 barTexture = "Addons\HealBot\Images\bar6.tga"
 healthBarClassColor = false
 barFontFlags = "OUTLINE"
 classification_rare = "Level %s|cffff66ff Rare"
 enableChatHoverTips = false
 colorGuildByReaction = true
 left = 1710.000142
 reactColoredBackdrop = false
 classification_trivial = "Level ~%s"
 iconSize = 25
 manaBar = false
 gradientColor = <table> {
 }
 pixelPerfectBackdrop = true
 fadeTime = 0.100000
 targetYouText = "<<YOU>>"
 showGuildRank = true
 barFontFace = "Fonts\FRIZQT__.TTF"
 barFontSize = 12
 fontSizeDelta = 2
 if_currencyQualityBorder = true
 overrideFade = false
 hideRealmText = false
 preFadeTime = 0.100000
 optionsLeft = 748.000061
 reactText = false
 showTarget = "last"
 showTTguildAfter = true
 tipColor = <table> {
 }
 hideDefaultBar = true
 healthBar = true
 colRace = "|cffddeeaa"
 classification_normal = "Level %s"
 colLevel = "|cffffcc00"
 reactColoredBorder = false
 classification_minus = "Level -%s"
 fontSize = 12
 showTargetedBy = true
 classification_worldboss = "Level %s|cffff0000 Boss"
 iconFaction = false
 showPlayerGender = false
 top = 112.999731
 healthBarText = "value"

**Comment by frozn** [comment]
Thanks for reporting this. I fixed it in this dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8345959/TipTac-dev.zip)

Working fine for you with this version, too?

**Comment by AutolycusWolf** [comment]
No problem, always glad to help. unfortunately I still get the same (?) error even with the dev version. Bug report follows:

9x TipTacItemRef\ttItemRef.lua:1831: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@TipTacItemRef\ttItemRef.lua"]:1831: in function `SetBackdropBorderColorLocked'
[string "@TipTacItemRef\ttItemRef.lua"]:2211: in function `quest'
[string "@TipTacItemRef\ttItemRef.lua"]:1033: in function <TipTacItemRef\ttItemRef.lua:1026>
[string "=[C]"]: in function `GameTooltip_AddQuestRewardsToTooltip'
[string "@Blizzard_Contribution\Blizzard_Contribution.lua"]:184: in function <...dOns\Blizzard_Contribution\Blizzard_Contribution.lua:175>

Locals:
self = TipTacItemRef {
 0 = <userdata>
 ApplyHooksToTips = <function> defined @TipTacItemRef\ttItemRef.lua:1406
 ADDON_LOADED = <function> defined @TipTacItemRef\ttItemRef.lua:1564
 ApplyWorkaroundForFirstMouseover = <function> defined @TipTacItemRef\ttItemRef.lua:285
 SetBackdropBorderColorLocked = <function> defined @TipTacItemRef\ttItemRef.lua:1825
 HookTips = <function> defined @TipTacItemRef\ttItemRef.lua:1559
 name = "ItemRef"
 CreateTooltipIcon = <function> defined @TipTacItemRef\ttItemRef.lua:184
 OnApplyConfig = <function> defined @TipTacItemRef\ttItemRef.lua:252
 ApplyHooksToCFGDFI = <function> defined @TipTacItemRef\ttItemRef.lua:1532
 ApplyHooksToGIFIC = <function> defined @TipTacItemRef\ttItemRef.lua:1546
 SetHyperlink_Hook = <function> defined @TipTacItemRef\ttItemRef.lua:421
}
tip = EmbeddedItemTooltip {
 0 = <userdata>
 BottomFontString = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 BottomOverlay = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 TextRight2 = EmbeddedItemTooltipTextRight2 {
 }
 TextLeft2 = EmbeddedItemTooltipTextLeft2 {
 }
 ttSetBackdropBorderColorLocked = false
 TopOverlay = <unnamed> {
 }
 waitingForData = true
 shoppingTooltips = <table> {
 }
 needsReset = true
 updateTooltipTimer = 0.200000
 TextRight1 = EmbeddedItemTooltipTextRight1 {
 }
 textRight2Font = "GameTooltipText"
 textLeft1Font = "GameTooltipHeaderText"
}
lockColor = true
r = 0.500000
g = 0.500000
b = 0.500000
a = 1
(*temporary) = nil
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 BottomFontString = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 BottomOverlay = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 TextRight2 = EmbeddedItemTooltipTextRight2 {
 }
 TextLeft2 = EmbeddedItemTooltipTextLeft2 {
 }
 ttSetBackdropBorderColorLocked = false
 TopOverlay = <unnamed> {
 }
 waitingForData = true
 shoppingTooltips = <table> {
 }
 needsReset = true
 updateTooltipTimer = 0.200000
 TextRight1 = EmbeddedItemTooltipTextRight1 {
 }
 textRight2Font = "GameTooltipText"
 textLeft1Font = "GameTooltipHeaderText"
}
(*temporary) = 0.500000
(*temporary) = 0.500000
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
cfg = <table> {
 fontFace = "Fonts\FRIZQT__.TTF"
 showRealm = "none"
 classification_elite = "Level %s|cffffcc00 Elite"
 barHeight = 6
 tipBackdropEdge = "Tooltips\UI-Tooltip-Border"
 backdropEdgeSize = 16
 hideFactionText = false
 powerBar = false
 fontFlags = ""
 barTexture = "Addons\HealBot\Images\bar6.tga"
 healthBarClassColor = false
 barFontFlags = "OUTLINE"
 classification_rare = "Level %s|cffff66ff Rare"
 enableChatHoverTips = false
 colorGuildByReaction = true
 left = 1710.000142
 reactColoredBackdrop = false
 classification_trivial = "Level ~%s"
 iconSize = 25
 manaBar = false
 gradientColor = <table> {
 }
 pixelPerfectBackdrop = true
 fadeTime = 0.100000
 targetYouText = "<<YOU>>"
 showGuildRank = true
 barFontFace = "Fonts\FRIZQT__.TTF"
 barFontSize = 12
 fontSizeDelta = 2
 if_currencyQualityBorder = true
 overrideFade = false
 hideRealmText = false
 preFadeTime = 0.100000
 optionsLeft = 748.000061
 reactText = false
 showTarget = "last"
 showTTguildAfter = true
 tipColor = <table> {
 }
 hideDefaultBar = true
 healthBar = true
 colRace = "|cffddeeaa"
 classification_normal = "Level %s"
 colLevel = "|cffffcc00"
 reactColoredBorder = false
 classification_minus = "Level -%s"
 fontSize = 12
 showTargetedBy = true
 classification_worldboss = "Level %s|cffff0000 Boss"
 iconFaction = false
 showPlayerGender = false
 top = 112.999731
 healthBarText = "value"

**Comment by AutolycusWolf** [comment]
No problem, always glad to help! Unfortunately I still get the same (?) error, even after using the dev version you directed me to. Bug report is as follows:

9x TipTacItemRef\ttItemRef.lua:1831: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@TipTacItemRef\ttItemRef.lua"]:1831: in function `SetBackdropBorderColorLocked'
[string "@TipTacItemRef\ttItemRef.lua"]:2211: in function `quest'
[string "@TipTacItemRef\ttItemRef.lua"]:1033: in function <TipTacItemRef\ttItemRef.lua:1026>
[string "=[C]"]: in function `GameTooltip_AddQuestRewardsToTooltip'
[string "@Blizzard_Contribution\Blizzard_Contribution.lua"]:184: in function <...dOns\Blizzard_Contribution\Blizzard_Contribution.lua:175>

Locals:
self = TipTacItemRef {
 0 = <userdata>
 ApplyHooksToTips = <function> defined @TipTacItemRef\ttItemRef.lua:1406
 ADDON_LOADED = <function> defined @TipTacItemRef\ttItemRef.lua:1564
 ApplyWorkaroundForFirstMouseover = <function> defined @TipTacItemRef\ttItemRef.lua:285
 SetBackdropBorderColorLocked = <function> defined @TipTacItemRef\ttItemRef.lua:1825
 HookTips = <function> defined @TipTacItemRef\ttItemRef.lua:1559
 name = "ItemRef"
 CreateTooltipIcon = <function> defined @TipTacItemRef\ttItemRef.lua:184
 OnApplyConfig = <function> defined @TipTacItemRef\ttItemRef.lua:252
 ApplyHooksToCFGDFI = <function> defined @TipTacItemRef\ttItemRef.lua:1532
 ApplyHooksToGIFIC = <function> defined @TipTacItemRef\ttItemRef.lua:1546
 SetHyperlink_Hook = <function> defined @TipTacItemRef\ttItemRef.lua:421
}
tip = EmbeddedItemTooltip {
 0 = <userdata>
 BottomFontString = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 BottomOverlay = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 TextRight2 = EmbeddedItemTooltipTextRight2 {
 }
 TextLeft2 = EmbeddedItemTooltipTextLeft2 {
 }
 ttSetBackdropBorderColorLocked = false
 TopOverlay = <unnamed> {
 }
 waitingForData = true
 shoppingTooltips = <table> {
 }
 needsReset = true
 updateTooltipTimer = 0.200000
 TextRight1 = EmbeddedItemTooltipTextRight1 {
 }
 textRight2Font = "GameTooltipText"
 textLeft1Font = "GameTooltipHeaderText"
}
lockColor = true
r = 0.500000
g = 0.500000
b = 0.500000
a = 1
(*temporary) = nil
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 BottomFontString = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 BottomOverlay = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 TextRight2 = EmbeddedItemTooltipTextRight2 {
 }
 TextLeft2 = EmbeddedItemTooltipTextLeft2 {
 }
 ttSetBackdropBorderColorLocked = false
 TopOverlay = <unnamed> {
 }
 waitingForData = true
 shoppingTooltips = <table> {
 }
 needsReset = true
 updateTooltipTimer = 0.200000
 TextRight1 = EmbeddedItemTooltipTextRight1 {
 }
 textRight2Font = "GameTooltipText"
 textLeft1Font = "GameTooltipHeaderText"
}
(*temporary) = 0.500000
(*temporary) = 0.500000
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
cfg = <table> {
 fontFace = "Fonts\FRIZQT__.TTF"
 showRealm = "none"
 classification_elite = "Level %s|cffffcc00 Elite"
 barHeight = 6
 tipBackdropEdge = "Tooltips\UI-Tooltip-Border"
 backdropEdgeSize = 16
 hideFactionText = false
 powerBar = false
 fontFlags = ""
 barTexture = "Addons\HealBot\Images\bar6.tga"
 healthBarClassColor = false
 barFontFlags = "OUTLINE"
 classification_rare = "Level %s|cffff66ff Rare"
 enableChatHoverTips = false
 colorGuildByReaction = true
 left = 1710.000142
 reactColoredBackdrop = false
 classification_trivial = "Level ~%s"
 iconSize = 25
 manaBar = false
 gradientColor = <table> {
 }
 pixelPerfectBackdrop = true
 fadeTime = 0.100000
 targetYouText = "<<YOU>>"
 showGuildRank = true
 barFontFace = "Fonts\FRIZQT__.TTF"
 barFontSize = 12
 fontSizeDelta = 2
 if_currencyQualityBorder = true
 overrideFade = false
 hideRealmText = false
 preFadeTime = 0.100000
 optionsLeft = 748.000061
 reactText = false
 showTarget = "last"
 showTTguildAfter = true
 tipColor = <table> {
 }
 hideDefaultBar = true
 healthBar = true
 colRace = "|cffddeeaa"
 classification_normal = "Level %s"
 colLevel = "|cffffcc00"
 reactColoredBorder = false
 classification_minus = "Level -%s"
 fontSize = 12
 showTargetedBy = true
 classification_worldboss = "Level %s|cffff0000 Boss"
 iconFaction = false
 showPlayerGender = false
 top = 112.999731
 healthBarText = "value"

**Comment by frozn** [comment]
I overlooked something. Fixed and tested it at legionfall construction table. I also added tiptac's styling to contribution reward/buff.

Here is the current dev version:
[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8353808/TipTac-dev.zip)

**Comment by AutolycusWolf** [comment]
Working like a charm now, just tested it!

**Comment by frozn** [comment]
That are great news. Thanks! 👍
